name: release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for PyPI provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build package
        run: |
          poetry build

      #- name: Publish to TestPyPI
      #  env:
      #    TWINE_USERNAME: __token__
      #    TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      #    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      #  run: |
      #    pip install twine
      #    python -m twine upload --repository-url $TWINE_REPOSITORY_URL dist/* -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Install python-semantic-release
        run: pip install python-semantic-release

      #- name: Release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
      #  run: semantic-release publish --pypi-token ${{ secrets.TEST_PYPI_TOKEN }}
